### ISSUE TITLE
AEPMobileServices missing as SPM?

### ISSUE THREAD

**Issue by BlackHornet** [adobe/aepsdk-analytics-ios#84]
Hello,

we have an iOS project targetting iOS14+ using SwiftUI + SPM and trying to find out a way to track a deeplink (UniversalLink) with campaign parameters.

As of the SwiftUI and iOS 14, we get the url in View.onOpenUrl
https://developer.apple.com/documentation/SwiftUI/View/onOpenURL(perform:)

And cannot use the MobileCore.collectLaunchInfo as we do not have the userInfo in that case.

For that I checked the documentation and found the MobileServices.trackAdobeDeepLink, but unfortunately we do not have the reference to the MobileServices yet, and wonder if that is the right method we should use, and how we can use them in our project setup.

Could you help us and maybe give us some guidance?

**Comment by ahmyr** [comment]
BlackHornet, mflknr,

We do not have SPM support for the MobileServices extension. You can see the note here:
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics-mobile-services

_iOS AEP (3.x) Mobile Services extension only supports Cocoapods. It does not work with Swift Package Manager or when included in your app as XCFramework dependency._

We don't intend to add this support because Mobile Services is set to end-of-life at the end of the year.
https://experienceleague.adobe.com/docs/mobile-services/using/eol.html?lang=en

Thanks,
Amber
